import turtle
turtle.shape('turtle')


def hhh() :
	turtle.forward(100)
	turtle.left(195)
	turtle.penup()
	turtle.forward(120)
	turtle.right(195)
	turtle.pendown()
	turtle.forward(140)
	turtle.left(180)
	turtle.forward(70)
	turtle.left(90)
	turtle.penup()
	turtle.forward(20)
	turtle.right(90)
	turtle.pendown()
	turtle.circle(50)


def aaa() :
	turtle.forward(180)
	turtle.right(180)
	turtle.forward(90)
	turtle.right(90)
	turtle.forward(40)

def rrr() :
	turtle.reset()
	turtle.penup()
	turtle.goto(-300,100)
	turtle.pendown()

def nnn() :
	turtle.forward(60)
	turtle.left(90)
	turtle.forward(150)

def ttt() :
	turtle.forward(130)
	turtle.right(180)
	turtle.forward(130)
	turtle.left(90)
	turtle.forward(80)
	turtle.left(90)
	turtle.forward(130)
	turtle.right(180)
	turtle.forward(130)
	turtle.left(90)
	turtle.forward(80)
	turtle.left(90)
	turtle.forward(130)


def uiui() :
	turtle.forward(180)
	turtle.right(90)
	turtle.forward(50)
	turtle.right(180)
	turtle.forward(230)

rrr()
for n in range(1) :

	hhh()
	turtle.right(180)
	turtle.penup()
	turtle.forward(100)
	turtle.left(90)
	turtle.forward(30)
	turtle.pendown()
	turtle.right(180)
	aaa()
	turtle.right(180)
	turtle.penup()
	turtle.forward(190)
	turtle.left(90)
	turtle.forward(80)
	turtle.pendown()
	nnn()
	turtle.left(90)
	turtle.penup()
	turtle.forward(200)
	turtle.right(90)
	turtle.forward(80)
	turtle.pendown()
	ttt()
	turtle.left(90)
	turtle.penup()
	turtle.forward(190)
	turtle.right(90)
	turtle.forward(20)
	turtle.right(90)
	turtle.pendown()
	turtle.forward(30)
	aaa()
	turtle.left(90)
	turtle.forward(120)
	turtle.right(180)
	turtle.forward(210)
	turtle.right(180)
	turtle.penup()
	turtle.forward(230)
	turtle.right(90)
	turtle.forward(70)
	turtle.pendown()
	hhh()
	turtle.penup()
	turtle.forward(80)
	turtle.left(90)
	turtle.forward(130)
	turtle.pendown()
	turtle.left(90)
	uiui()
	turtle.exitonclick()

